### PR TITLE
P#57347 Make explanation for title in URL translatable

### PR DESCRIPTION
**Pull request by vu-vuong-esg**
P#57347 Make explanation for title in URL translatable

### CODE REVIEW

**Comment by jayay** [comment]
@vu-vuong-esg could you please check what PHPStan found out? (It's annotated in the diffs)

**Comment by vu-vuong-esg** [comment]
> @vu-vuong-esg could you please check what PHPStan found out? It's annotated in the diffs and seems to also have happend in master. It's got to be a change PHPStan introduced in version 1.0.0

Yes. I will check about the changes.

**Review by jayay — APPROVED** [review]

**Comment by michaelarnold-dev** [comment]
@tung-le-esg Could you please resolve that conflicts?

**Comment by tung-le-esg** [comment]
> @tung-le-esg Could you please resolve that conflicts?

Okay, sure

**Pull request merged**
