### PR TITLE
Contact form interest lead to mail with xml

### PR DESCRIPTION
**Pull request by hungnc89**

### CODE REVIEW

**Review by jayay — APPROVED** [review]
Thank you! I like how clean your solution is. My tests look good except that the message field doesn't appear in the front-end after selecting it in the back-end. I don't know if your change is to blame here, though.

**Comment by hungnc89** [comment]
@jayay Please recheck this PR, I updated search criterias and origin website on the email body

**Review by jayay — APPROVED** [review]

**Comment by hungnc89** [comment]
@jayay I updated the typo and 1 more problems. I used the message field to append the search criteria but now the requirement is remove the message field. So do you have any suggestion where to put the search criterias into the email body?

**Review by jayay — APPROVED** [review]

**Comment by jayay** [comment]
> I used the message field to append the search criteria but now the requirement is remove the message field.

Could you please give me the ticket number?

**Comment by hungnc89** [comment]
> > I used the message field to append the search criteria but now the requirement is remove the message field.
> 
> Could you please give me the ticket number?

BE - 43021, Titel: [WP] Contact form + interested form should lead to mail with XML and address - Correct spelling mistak and remove message from mail (Folgeaufgabe #2182203)

**Pull request merged**
