### PR TITLE
P#57343 Make number of list views to display configurable

### PR DESCRIPTION
**Pull request by hungnc89**

### CODE REVIEW

**Comment by hungnc89** [comment]
@jayay could you review this PR?

**Comment by hungnc89** [comment]
> Looks good so far! If you wanted to write some tests for this, you could add wrapper methods for the `*_screen_*` functions in the `WPScreenWrapper` class.

@jayay Thank u, I'll try it

**Review by jayay — APPROVED** [review]
I think this is good, it should be given a try.

**Review by jmaas-onoffice — APPROVED** [review]
Trigger new zip.

**Review by jmaas-onoffice — APPROVED** [review]
Trigger new zip.

**Review by jmaas-onoffice — APPROVED** [review]
Trigger new zip.

**Pull request merged**
