### PR TITLE
P#60739 Remove unsupported data types - Data types still visible in some lists revert

### PR DESCRIPTION
**Pull request by yeneastgate**
…ve field

### CODE REVIEW

**Review by hungnc89 — APPROVED** [review]

**Review by LongTrong-exe — APPROVED** [review]

**Review by LongTrong-exe — APPROVED** [review]

**Comment by hungnc89** [comment]
- Tester tested
- Video:

https://user-images.githubusercontent.com/72601287/174043037-46ae7d78-367e-4349-b7a5-d4043a40da5d.mp4

**Review by jmaas-onoffice — APPROVED** [review]

**Review by jmaas-onoffice — COMMENTED** [review]
It seems that with v3.2 I already cannot select the unsupported data types in the field selection. This makes it difficult to test this change.

Do you have a version where the unsupported types can be added to the field list so that I can test the update?

**Comment by jmaas-onoffice** [comment]
I'm a bit confused because as far as I can see this change has not been released. So how could it be that the issue is fixed, but we still have this PR open?

**Comment by yeneastgate** [comment]
> I'm a bit confused because as far as I can see this change has not been released. So how could it be that the issue is fixed, but we still have this PR open?

The reason is that in the "loadLanguage()" function in the "Fieldnames.php" file, "'realDataTypes' => true".
This issue was fixed in pull request #109.
image

**Comment by yeneastgate** [comment]
> It seems that with v3.2 I already cannot select the unsupported data types in the field selection. This makes it difficult to test this change.
> 
> Do you have a version where the unsupported types can be added to the field list so that I can test the update?

you can return master and comments line code on "FieldLoaderGeneric.php" and "Fieldnames.php"
image
image

**Review by jmaas-onoffice — APPROVED** [review]

**Comment by jmaas-onoffice** [comment]
Ok, if I understand this PR correctly, it only adds some code so that on installation all those unsupported fields are removed, if they are used in a form, list or estate detail. Is that correct?

If so, I think maybe it's best if we close this PR, because testing those database deletions is not easy. At the same time, the fields are already not selectable for the fieldlist anymore. So the worst thing that can happen is that someone had added one of the unsupported fields a long time ago and it still is in their field list. But since the field is not output on the frontend, nothing breaks.

All in all, if I understand it correctly, I think it's best if we close this PR without merging, because the underlying problem has already been fixed. Sorry for not realizing this sooner!

**Pull request closed without merging**
