### PR TITLE
Fix Error File onoffice-for-wp-websites-de_DE.po When Translate Exists

### PR DESCRIPTION
**Pull request by tang-hien-egs**

### CODE REVIEW

**Comment by tang-hien-egs** [comment]
@jmaas-onoffice, i find error when translate multi languages at file onoffice-for-wp-websites-de_DE.po at master with string exist

**Comment by jmaas-onoffice** [comment]
Could you explain your workflow with these files?

I thought they were auto-generated, which would mean that the error would come back. Or how is the .po file created?

**Comment by vu-vuong-esg** [comment]
> Could you explain your workflow with these files?
> 
> I thought they were auto-generated, which would mean that the error would come back. Or how is the .po file created?

@jmaas-onoffice  Luckily, branch master that fixed my issue found out !

**Comment by vu-vuong-esg** [comment]
i will close this PR !

**Comment by jmaas-onoffice** [comment]
> > Could you explain your workflow with these files?
> > I thought they were auto-generated, which would mean that the error would come back. Or how is the .po file created?
> 
> @jmaas-onoffice Luckily, branch master that fixed my issue found out !

Ok, that's good. :)

**Pull request closed without merging**
