### PR TITLE
#11122 configuration of pagination

### PR DESCRIPTION
**Pull request by hungnc89**

### CODE REVIEW

**Review by jayay — APPROVED** [review]
Looks good. Can this be tested using unit or integration tests?

**Comment by hungnc89** [comment]
@jayay I updated the paging function to the templates. Can you have a look?

**Comment by jayay** [comment]
Looks good to me. Regarding the test: do you think it is possible to check if the pagination works if a new test was added to `TestTemplateEstateDefaultDetail`?

**Comment by hungnc89** [comment]
> Looks good to me. Regarding the test: do you think it is possible to check if the pagination works if a new test was added to `TestTemplateEstateDefaultDetail`?

@jayay let me check it and reply

**Comment by hungnc89** [comment]
> Looks good to me. Regarding the test: do you think it is possible to check if the pagination works if a new test was added to `TestTemplateEstateDefaultDetail`?

Hi @jayay, I don't add pagination to default detail template because my current theme using it. It does not have pagination. The pagination only appears in other pages.

**Pull request merged**
