### PR TITLE
P#55975 improve sorting controls 17550

### PR DESCRIPTION
**Pull request by hungnc89**

### CODE REVIEW

**Comment by jayay** [comment]
@hungnc89 Thank you. Could you please look after indents and tests?

**Review by jayay — DISMISSED** [review]

**Comment by jayay** [comment]
@hungnc89 could you please resolve the conflicts? Thank you!

**Comment by jmaas-onoffice** [comment]
@LongTrong-exe I just noticed that this might conflict with #109. Can we merge both PRs into one? Or how would you like to continue?

**Comment by LongTrong-exe** [comment]
> @LongTrong-exe I just noticed that this might conflict with #109. Can we merge both PRs into one? Or how would you like to continue?

Yes, I'll try merging them into one

**Comment by jmaas-onoffice** [comment]
Should we close this and continue in #109?

**Comment by jmaas-onoffice** [comment]
Let's close this and continue in #109.

**Pull request closed without merging**
