### PR TITLE
P#72883 Uninstall does not clear all settings

### PR DESCRIPTION
**Pull request by dai-eastgate**

### CODE REVIEW

**Comment by jmaas-onoffice** [comment]
Do you think there is a way to ensure that we don't forget to remove options on uninstall?

**Comment by LongTrong-exe** [comment]
@jmaas-onoffice I think use sql query to get all options in db with prefix "onoffice" or "oo".

**Comment by jmaas-onoffice** [comment]
That seems a bit dangerous. Is there a way to handle this in the code? For example a way to register new field that automatically remembers them for deletion when the plugin is uninstalled? Or a test that installs the plugin and uninstalls it and checks the database?

If this is too much work for too little value, that's ok. I am just curious. ;)

**Comment by dai-eastgate** [comment]
Do you want to store all options that we registered as a json array? In the uninstall we can loop through that array & delete one by one and finally we delete the option that holds all options.

**Comment by jmaas-onoffice** [comment]
I don't know what would be a good approach. 😅

Maybe it's best if we merge this, because this definitely works. And if you happen to find an improvement, we can always make a new PR. :)

**Pull request merged**
