### PR TITLE
P#65163 Detail page leads to error when it has a parent page (new PR after revert)

### PR DESCRIPTION
**Pull request by jmaas-onoffice**
I merged #182, but unfortunately I then noticed a bug with WPML that leads to an infinite redirect loop. So I have to reopen this PR. Sorry for the confusion.

The bug is that when I am on the detail page and I switch the language, there is an infinite redirect loop. You can test this on https://2.wptest.onofficeweb.com/, I have installed WPML there.

### CODE REVIEW

**Review by onOffice-Web — DISMISSED** [review]

**Comment by LongTrong-exe** [comment]
This's my test video:

https://user-images.githubusercontent.com/101325858/163112620-480a86b6-dc99-4625-a24b-9b731fe69da6.mp4

**Comment by LongTrong-exe** [comment]
@jmaas-onoffice Could you please review this PR?

**Review by onOffice-Web — APPROVED** [review]

**Comment by jmaas-onoffice** [comment]
Very nice, it works now! :)

I have noticed one small issue that is a bit related: The links to the detail pages are missing a trailing slash.

grafik

This leads to an extra redirect, which can hurt SEO.

grafik

Can you see if we can make the links have a trailing slash, so that the redirect doesn't happen?

**Review by onOffice-Web — CHANGES_REQUESTED** [review]
For your information: I can't request changes, because I opened this PR, so I have to use this account for that.

**Comment by LongTrong-exe** [comment]
@jmaas-onoffice I checked as u said. Redirection is still good when the slash is added after the links

**Comment by LongTrong-exe** [comment]
Do you need me to push the code?

**Comment by jmaas-onoffice** [comment]
@LongTrong-exe If you changed something to make it work, I think you should push the code. Or why did you ask? :)

**Review by onOffice-Web — APPROVED** [review]
On behalf of @jmaas-onoffice.

**Comment by jmaas-onoffice** [comment]
@LongTrong-exe So is this code finished from you part and I can test it? :)

**Comment by hungnc89** [comment]
- Tester tested
- Video :

https://user-images.githubusercontent.com/72601287/163983761-92ad2789-a32a-426e-860a-84df67e9ce6c.mp4

**Review by onOffice-Web — CHANGES_REQUESTED** [review]
Unfortunately it seems that now the redirection is broken.

When you visit https://2.wptest.onofficeweb.com/front-page/detail/35-broken/, you should be redirected to https://2.wptest.onofficeweb.com/front-page/detail/35-og119/. But instead you stay at https://2.wptest.onofficeweb.com/front-page/detail/35-broken/.

Can you please have a look at the test instance and what the issue is? (Note that the plugin version shows up as `98c4fd6`, but it should actually be [`2.22.5-54-g98c4fd66`](https://github.com/onOfficeGmbH/oo-wp-plugin/pull/211#issuecomment-1102160497).)

**Comment by LongTrong-exe** [comment]
@jmaas-onoffice Oh, this bug doesn't happen with old WPML version.

**Comment by LongTrong-exe** [comment]
My test video:
https://user-images.githubusercontent.com/101325858/165433124-1a60c256-995c-4d92-8b84-ae33c82ad094.mp4

**Comment by hungnc89** [comment]
- Tester retested 
- Video :

https://user-images.githubusercontent.com/72601287/165461815-c7a30bbe-dec5-403b-ba0f-9c95d0d9418e.mp4

**Comment by LongTrong-exe** [comment]
@jmaas-onoffice Could you please review this PR?

**Review by onOffice-Web — APPROVED** [review]

**Review by onOffice-Web — CHANGES_REQUESTED** [review]
Now we are back to a previous error message. :(

Could you please have a look at the following issues?
- https://github.com/onOfficeGmbH/oo-wp-plugin/issues/226
- https://github.com/onOfficeGmbH/oo-wp-plugin/issues/227

**Comment by LongTrong-exe** [comment]
https://user-images.githubusercontent.com/101325858/165676569-4f54a560-5527-492b-9b29-ce88eff4f641.mp4

**Comment by LongTrong-exe** [comment]
@jmaas-onoffice Could you please review this PR?

**Review by onOffice-Web — APPROVED** [review]

**Review by onOffice-Web — APPROVED** [review]

**Review by onOffice-Web — CHANGES_REQUESTED** [review]
I don't know why the development .zip action wasn't triggered. I tested on a .zip I created manually.

One of the issues is resolved. :)
I still have this issue: https://github.com/onOfficeGmbH/oo-wp-plugin/issues/226

**Comment by LongTrong-exe** [comment]
@jmaas-onoffice I tried on 3 different pc, but that bug didn't happen. Can you try reinstalling wp on your server? Or ask jakob about this?

**Comment by LongTrong-exe** [comment]
@jmaas-onoffice Could you please review new commit? I tested my new code on your test instance (https://2.wptest.onofficeweb.com/) and it worked.

**Review by onOffice-Web — APPROVED** [review]

**Comment by jmaas-onoffice** [comment]
Awesome, I tested it, and it seems to work great! Thanks! :)

**Review by onOffice-Web — APPROVED** [review]

**Pull request merged**
