### PR TITLE
P#54053 Activating option in api user's rights settings crashes wordpress backend (Prio-Projekt)

### PR DESCRIPTION
**Pull request by vu-vuong-esg**
P#54053 Activating option in api user's rights settings crashes wordpress backend

### CODE REVIEW

**Comment by tung-le-esg** [comment]
@jayay This option in API user's right that crashed WordPress backend has been removed from onOffice enterprise.

**Comment by jayay** [comment]
@tung-le-esg Thanks for the heads up, I'll ask about it

**Comment by michaelarnold-dev** [comment]
ok, I took the project off the board.

**Comment by jayay** [comment]
Good. I'm closing this then. Sorry for the time lost

**Pull request closed without merging**
