### PR TITLE
P#51791 Make address creation configurable and explain duplicate check

### PR DESCRIPTION
**Pull request by hungnc89**

### CODE REVIEW

**Comment by jayay** [comment]
Looks good! Is this ready for testing?

**Comment by vu-vuong-esg** [comment]
> Looks good! Is this ready for testing?

yes, it is ready for test.

**Review by jayay — APPROVED** [review]

**Review by jayay — APPROVED** [review]

**Comment by michaelarnold-dev** [comment]
@vu-vuong-esg Could you please resolve the conflicts?

**Review by jayay — APPROVED** [review]

**Comment by michaelarnold-dev** [comment]
@tung-le-esg  Could you please check the tests? Some are cancelled, some failed. Thank you in advance

**Comment by tung-le-esg** [comment]
> @tung-le-esg Could you please check the tests? Some are cancelled, some failed. Thank you in advance

Okay. Let me check

**Comment by hungnc89** [comment]
@michaelarnold-dev Here you are

**Pull request merged**
