### PR TITLE
Task 10929 Message-field-do-not-config-backend-interest-form

### PR DESCRIPTION
**Pull request by hungnc89**

### CODE REVIEW

**Comment by jayay** [comment]
@yenncc and @hungnc89 I think something weird happened when c1728bb got merged into this branch. Could you please try to undo this and rebase it from master again? It's not being recognized as a merge-commit.

**Comment by jayay** [comment]
You can do that in a new branch, if you want to

**Comment by jayay** [comment]
@hungnc89 would you please create a new PR for this? On the branch itself it (correctly) says

> This branch is 5 commits ahead, 9 commits behind master.

**Comment by nglelinh** [comment]
open the #171 to replace this

**Comment by jayay** [comment]
OK, closing this then.

**Pull request closed without merging**
